language: node_js
if: branch != gh-pages
node_js:
  - 16

install:
  - npm ci

script:
  - npm run docs:build
  - echo 'docs.commercio.network' > docs/.vuepress/dist/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master