language: node_js
if: branch != gh-pages
node_js:
  - 16

install:
  - npm ci

script:
  - make build-docs

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master