accounts:
  - name: alice
    coins: ['20000000000uccc', '200000000000ucommercio']
    #address: "did:com:18h03de6awcjk4u9gaz8s5l0xxl8ulxjctzsytd"
    mnemonic: 'gaze apart pen defense tomorrow index again pool earth force napkin noble elevator payment hawk trip cute gown fade wear swallow alert lemon people'
  - name: bob
    coins: ['10000000000uccc', '100000000000ucommercio']
    #address: "did:com:1829s409tjju2luhudq5dfeus6je3vfdnjv9tpn"
    mnemonic: 'special chest leaf section reunion inflict busy blouse inflict kid alcohol hazard embody mosquito green turkey street very lab forest gain disease hollow bomb'
  - name: gov
    coins: ['10000000000uccc', '100000000000ucommercio']
    #address: "did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm"
    mnemonic: 'bonus raccoon material jump tired under cup senior wash peace cook mansion nice rely outside atom surface maid dune poet hold forum electric accuse'
  - name: serena
    coins: ['50000000000uccc', '500000000000ucommercio']
    #address: did:com:1nh557a0gmn0cwnrvefs7xll4986xsu27wnfzw2
    mnemonic: 'bracket drink predict south arrange helmet accuse save raccoon wave tent nation tooth depth limb simple dinosaur faculty nest siege myth guard comic cattle'
  - name: giovanna
    coins: ['1000000uccc', '5000000000ucommercio']
    #address: did:com:1q7hszn4gtwdrpylldw32ex2p7cpd4qvj00yg8t
    mnemonic: 'cement hungry buzz fit home source answer juice metal sock lucky inherit foster scout engine switch sail crop ketchup hard need genre crumble cabbage'
  - name: marta
    coins: ['1000000uccc', '5000000000ucommercio']
    #address: did:com:17zx4vs4fhy7c2yv4gzq5u9uqutlzqv7xyq9y38
    mnemonic: 'skin repair chuckle boil culture strategy minimum fitness trigger confirm paper off demise long member artefact trip universe spice town sting stove alert load'
validator:
  name: alice
  staked: '100000000ucommercio'
client:
  vuex:
    path: 'vue/src/store'
  openapi:
    path: 'docs_3_0/static/openapi.yml'
faucet:
  name: bob
  coins: ['5uccc', '100000ucommercio']
genesis:
  chain_id: 'localnet'
  app_state:
    government:
      governmentAddress: 'did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm'
    vbr:
      poolAmount:
        - denom: 'ucommercio'
          amount: '10000000.000000000000000000'
      rewardRate: '0.010000000000000000'
    staking:
      params:
        bond_denom: 'ucommercio'
    commerciokyc:
      trusted_service_providers:
        ['did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm']
      memberships:
        - expiry_at: '2022-03-21T00:00:00Z'
          membership_type: 'black'
          owner: 'did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm'
          tsp_address: 'did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm'
      liquidity_pool_amount:
        - amount: '1000000000000'
          denom: 'ucommercio'
    commerciomint:
      Positions:
        - ID: '090ca0c2-cf00-4119-8307-b51413a00cf4'
          collateral: '7'
          created_at: '2021-07-22T13:18:44.598560074Z'
          credits:
            amount: '10'
            denom: 'uccc'
          exchange_rate: '0.900000000000000000'
          owner: 'did:com:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm'
      collateral_rate: '0.900000000000000000'
      freeze_period: '1814400s'
